### ISSUE TITLE
Open to pull requests for more formats and file streaming support?

### ISSUE THREAD

**Issue by flipcoder** [NicklasTegner/PyAL#2]
I've added support for more formats in my fork using soundfile:

https://github.com/flipcoder/PyAL

I didn't know if this was beyond the scope of your project, but I made the dependency optional with a fallback if soundfile is not installed.  I just did this today so it's not 100% tested yet.

If you're open to pull requests, I can also add file streaming support.

**Comment by NicklasTegner** [comment]
I am very open for pull requests.
Sidenote, I know the readme states, that you can only install it from source, but it is actually on pypi here: https://pypi.org/project/python-openal/
As long as you can test your additions some more (if it needs to be) I am open for a pr

**Comment by flipcoder** [comment]
Great, thanks. I will continue working on the additions.

**Comment by NicklasTegner** [comment]
@flipcoder Hello.
Any updates as to when/if I could expect a pull request with your additions?

**Comment by flipcoder** [comment]
I started using PyOpenAL for my project instead.  My fork of PyAL has ogg support IIRC but I never finished adding streaming.  I hit an issue with libsoundfile when doing streaming due to it not being able to resample.  So if you ever add streaming the future, I'd recommend using PyOGG instead libsoundfile like I did.  I can send a pull request of my ogg changes if you'd like.

**Comment by NicklasTegner** [comment]
A pull request would still be welcome yes.
