### ISSUE TITLE
error while trying the HRTF example

### ISSUE THREAD

**Issue by Tetsujinfr** [NicklasTegner/PyAL#5]
Hi, thanks for your great repo!
I am trying the different examples, the 3D audio example works fine, however the HRTF example does crash.
I have the following error message below, which I can not find help for on the wed just yet:
I am on Linux, Ubuntu 18.04, on Jetson Xavier NX (Jetpack 4.4).
Error is:
> AttributeError: module 'pyglet.media.drivers.openal.lib_alc' has no attribute 'ALC_NUM_HRTF_SPECIFIERS_SOFT'

Did I miss a dependency or a file somehow?

**Comment by NicklasTegner** [comment]
Hi @Tetsujinfr 
Thanks for filling the issue.
From my preliminary research, it looks like the OpenAL you have installed (if any) doesn't have support for HRTF.
For context, I have only tested it on Windows, Python 3x, with OpenALSoft which has HRTF.

For more information, you could try taking a look at the following page: https://pyglet.readthedocs.io/en/latest/programming_guide/media.html

Let me know what you think / what you find.

**Comment by Tetsujinfr** [comment]
thanks for your message.

So I installed openal-soft, first through apt-get install libopenal-dev, but I had the same error message when trying the HRTF example.
Then, I removed the libopenal-dev and build openal-soft from source and installed it with make install, but I still have the same error when trying to run the HRTF example.
Not sure if I am missing a library binding or if I need to setup something.

Maybe the pyglet lib I installed does not support HRTF properly. I am running out of ideas though.

I am trying to simulate 3D sounds with proper positioning, which I think requires HRTF to work really well.

**Comment by NicklasTegner** [comment]
hi @Tetsujinfr 
After taking a closer look at the examples, it looks like they were using pyglets OpenAL driver instead of this library.
I have updated the examples, so if you could pull and try again, that would be amazing.

**Comment by Tetsujinfr** [comment]
Thank you for acting onto it so quickly.
So I pulled the repo again and tried the updated examples.
I do not have the old error as before, however I now have errors for both examples I tried, that is to say the 3D stereo and the HRTF examples. The errors seems to be of the same nature, and given I am just a basic python programmer I cannot find what is wrong.
Somehow, the code does not recognise the types from the openal ALuint or ALCint bindings. Not sure why really, maybe some python typo?

Here is the error I have for the 3D Audio example:
> File "OpenAL_3D.py", line 111, in __init__
> self.buf = al.ALuint(0)
> AttributeError: module 'openal.al' has no attribute 'ALuint'

Here is the error I have for the 3D Audio example:
> File "OpenAL_HRTF.py", line 94, in __init__
> self.hrtf_buffers = [alc.ALCint(),alc.ALCint*4,alc.ALCint()]
> AttributeError: module 'openal.alc' has no attribute 'ALCint'

Hopefully you can spot what is not working, but I feel this is moving into the right direction.

**Comment by NicklasTegner** [comment]
hi @Tetsujinfr 
That is very stringe. Those properties (ALuint and ALCint) doesexists in "openal.alc" and "openal.al" respectively.
My only other guess right now, would be, that you have some other openal python library installed.
 
For reference, I can get those same examples to work, here on my Windows 10 box and through WSL.

**Comment by Tetsujinfr** [comment]
You were correct, I did install some other python openAL libraries which did conflict with your I guess.
I uninstalled them and now the examples works better but not fully just yet.
The 3D audio example works just fine.

For the HRTF example, I can hear 3 loops of the tone moving from left to right.
The non hrtf and first hrtf loops work fine.

The third loop, for the hrtf 48000 hertz simulation, does thraw a non critical error though.
I did add a few debug prints statements, and I can see that the example finishes properly however, there is a non critical error message when the third loop tries to enable the 48000 hertz hrtf default table, which indeed returns false. So I assume that the 48000 hertz HRTF loop does is played without HRTF then.
Being not very familiar with openAL, I wonder how to check which table the code is really using, for instance I am not sure which table is used by the first HRTF loop in the example file. I see that there are two MHR files in the example folder, one 44100 hertz and one 48000 hertz, but I do not see when those would get loaded in your example code.
The error message makes me doubt about which table are loaded and from where, in the example, since the error message refers to the default hrtf mhr file from the openal-soft install I think.

Here is the error message:
> AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/local/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
> AL lib: (EE) GetLoadedHrtf: Failed to load /usr/local/share/openal/hrtf/Default HRTF.mhr

Do you have an idea on what I am doing wrong, or if I need to put some arguments or code to clarify which hrtf tables are loaded before executing the sound simulation?

thank you very much for your amazing help so far.

**Comment by NicklasTegner** [comment]
Hi.
It looks like you either (from your previous installation of OpenAL) or for some other reason, still have some files left in "/usr/local/share/openal/"
because, from your output above, it's finding and trying to use those hrtf tables (in "/usr/local/share/openal/") instead of the ones in the example directory.
You could try the following, to see if that fixes the problem.

* Move (not copy) the "/usr/local/share/openal/" folder to another place.
* Or just try to move or delete the "/usr/local/share/openal/hrtf" subfolder.


For reference, when I run the hrtf example, the output I get is as follows.
Note: the number "3" (before the trues) are the number of available hrtf tables.

> $ python OpenAL_HRTF.py
Usage: OpenAL_HRTF.py wavefile
    Using an example wav file...
3
True
True

**Comment by Tetsujinfr** [comment]
thank you, that did work just fine!

I have 4 tables listed when I execute the program, so 5 minus the one I just moved away from the usr/local/share/openal folder.
That is still one more than on your system, so I guess there is another mhr files somewhere I may want to clean up.
I am not sure how I can get more details on how openal is sourcing those mhr table files, do you know?

I am going to start "playing" with your api, and I have another set of questions for you, for instance what are the units in the position property of the listener or player classes, meters?
But please let me know if I should open another issue and close this one, than continuing on this thread

I think your library is great and a bit more examples like through a tutorial for dummies (like me) would be great.
I ll be happy to share some (dirty) code I will put together if that helps.

**Comment by NicklasTegner** [comment]
hi @Tetsujinfr 
I would say, that since the hrtf example is working for you now, I would open a separate issue with more generic or other topiced questions.
For your question about units of measurement in the position of the listener and player (and other places) that is a non-determed unit. To say, open al doesn't care if you use feet, cm, meters or inches, the only real thing to keep in mind, is that it needs to be consistent, a quick google search showed me [this](http://openal.996291.n3.nabble.com/Units-for-position-td1581.html) but you can do more research on that, by just googling something like "open al unit of measurement" or "open al position unit".

**Comment by NicklasTegner** [comment]
In addition, I can work on improving the examples, clearing / rewriting the documentation and maybe making a intro tutorial.

**Comment by Tetsujinfr** [comment]
Thanks for your help on this issue, closing it now since all works great on my side.
